app = "rock-stack"
primary_region = "hkg"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 3_000
min_machines_running = 0
processes = ["app"]

[[http_service.checks]]
grace_period = "10s"
interval = "30s"
method = "GET"
path = "/healthcheck"
timeout = "5s"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "1gb"

[env]
DATABASE_URL = "file:./data/sqlite.db"
